---
apiVersion: v1
kind: Service
metadata:
  name: echoserver
  namespace: {{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "echoserver")) | nindent 2 }}
spec:
  ports:
    - port: 8081
      targetPort: http
      protocol: TCP
      name: http
  type: ClusterIP
  selector:
    app: echoserver
